# Generated by Django 2.1.1 on 2018-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('identityKey', models.CharField(max_length=100)),
                ('registrationId', models.CharField(max_length=100)),
                ('preKeys', models.CharField(max_length=10000)),
                ('signedPreKey', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
