# Generated by Django 2.1.1 on 2019-04-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='identityKey',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='api.Device'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.Device'),
        ),
        migrations.AlterField(
            model_name='prekey',
            name='publicKey',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='signedprekey',
            name='publicKey',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='signedprekey',
            name='signature',
            field=models.CharField(max_length=88),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'address')},
        ),
    ]
